# This file controls the configuration for your Supabase project.
# For detailed documentation, visit: https://supabase.com/docs/guides/hosting/overview

# Project configuration
project_id = "stvmsmqnrwiifwthlppy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://stvmsmqnrwiifwthlppy.supabase.co"
additional_redirect_urls = [
  "http://localhost:3000",
  "https://stvmsmqnrwiifwthlppy.supabase.co"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.external]
enable_signup = false
