version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Assign reviewers
    reviewers:
      - "Kabi10"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "automerge"
    # Specify version update preferences
    versioning-strategy: increase
    # Group dependencies updates
    groups:
      dependencies:
        patterns:
          - "*"
    # Raise pull requests for version updates against the `develop` branch
    target-branch: "develop"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "Kabi10"
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    target-branch: "develop" 