- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "priority: critical"
  color: "b60205"
  description: "Must be fixed ASAP"

- name: "priority: high"
  color: "d93f0b"
  description: "Should be fixed soon"

- name: "priority: medium"
  color: "fbca04"
  description: "Should be fixed in near future"

- name: "priority: low"
  color: "0e8a16"
  description: "Nice to have"

- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by other issues/work"

- name: "status: in progress"
  color: "0052cc"
  description: "Currently being worked on"

- name: "status: review needed"
  color: "fbca04"
  description: "Ready for review"

- name: "type: ui"
  color: "c2e0c6"
  description: "User interface and experience"

- name: "type: backend"
  color: "d4c5f9"
  description: "Backend related changes"

- name: "type: testing"
  color: "fef2c0"
  description: "Testing related changes" 