-- Drop existing RLS policies on company_news table if they exist
DO $$ 
BEGIN
    EXECUTE (
        SELECT string_agg('DROP POLICY IF EXISTS "' || policyname || '" ON company_news;', E'\n')
        FROM pg_catalog.pg_policies 
        WHERE tablename = 'company_news'
    );
END $$;

-- Create the company_news table
CREATE TABLE IF NOT EXISTS public.company_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    url TEXT NOT NULL,
    source VARCHAR(255),
    published_at TIMESTAMP WITH TIME ZONE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_company_news_company_name ON public.company_news(company_name);
CREATE INDEX IF NOT EXISTS idx_company_news_published_at ON public.company_news(published_at);

-- Add RLS policies
ALTER TABLE public.company_news ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access to company news"
ON public.company_news
FOR SELECT
TO public
USING (true);

-- Allow authenticated users to insert news
CREATE POLICY "Allow authenticated users to insert news"
ON public.company_news
FOR INSERT
TO authenticated
WITH CHECK (true);

COMMENT ON TABLE public.company_news IS 'Stores news articles related to companies'; 