name: 'Auto Merge Develop to Main'

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests and linting
        run: |
          npm run lint
          npm run test --if-present

  auto-merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Create and merge pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="auto-merge/develop-to-main-$(date +%s)"
          git checkout -b $BRANCH_NAME develop
          
          gh pr create \
            --base main \
            --head $BRANCH_NAME \
            --title "Auto-merge: Develop to Main" \
            --body "Automatically created PR to merge develop into main" \
            --label "auto-merge"
          
          sleep 5
          
          PR_NUMBER=$(gh pr list --head $BRANCH_NAME --json number -q '.[0].number')
          gh pr merge $PR_NUMBER --merge --delete-branch 