name: "Sync Wiki"

on:
  push:
    paths:
      - "resources/**"
    branches:
      - "main"

jobs:
  sync-wiki:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
      
      - name: "Push Wiki Changes"
        uses: "Andrew-Chen-Wang/github-wiki-action@v4"
        env:
          WIKI_DIR: "resources/"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }} 